'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("eService.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM tblstk_movement WHERE vchCust_Code = @vchCust_Code;
        '''INSERT INTO tblstk_movement
        '''(vchCust_Code,vchItem_Code,intOffset_Bal,dtRecordAdded)
        '''SELECT @vchCust_Code,COALESCE(a.vchItem_Code,b.vchItem_Code)vchItem_Code,COALESCE(totPO_Qty,0)-COALESCE(totOffset_Qty,0) totBal_Qty,now() FROM
        '''(SELECT @vchCust_Code as vchCust_Code,vchItem_Code,SUM(intQty) totPO_Qty 
        '''	FROM tblpo_headers a
        '''	INNER JOIN tblpo_details b on a.vchPO_Code = b.vchPO_Code
        '''	WHERE a.vchStatus = &apos;CLOSED&apos; AND b.vchStatus = &apos;CLOSED&apos; AN [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property string_recalcStockMovement() As String
            Get
                Return ResourceManager.GetString("string_recalcStockMovement", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
